#server
server:
  port: 8088
  session:
    timeout: 30
  context-path: /

#spring
spring:
  #datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot2?useUnicode=true&characterEncoding=utf8
    username: root
    password: xwbing
  #jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
        dialect : org.hibernate.dialect.MySQL5Dialect
  #aop
  aop:
    auto: true # Add @EnableAspectJAutoProxy
    proxy-target-class: false
  #mail
  mail:
    host: smtp.163.com
    username: xiangwbs@163.com
    password: xwbing900511 #邮箱设置里获取的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true #授权
          starttls:
            enable: true
            required: true

#redis
redis:
  host: 192.168.11.202
  port: 6379
  password:
  timeout: 10000
  maxTotal: 8 #最大连接数
  maxIdle: 8  #最大空闲数
  minIdle: 0  #最小空闲数

#log
logging:
  config: classpath:log4j2.xml

